apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-http-mock-multiple
  annotations:
    github.com/project-slug: danbordeanu/go-http-mock-multiple
spec:
  type: other
  lifecycle: unknown